#-----------------------------------------------------#
#                                                     #
#                Database Properties                  #
#                                                     #
#-----------------------------------------------------#
default:
  database:
    host: 'localhost'
    port: 27017
    name: 'redseal'